booth/urls.py
from django.urls import path

from . import views

app_name = 'booth'
urlpatterns = [
    path('', views.activeelection, name='index'),
    path('registerindex', views.registerindex, name='registerindex'),
    path('register', views.register, name='register'),
    path('electionactions', views.electionactions, name='electionactions'),
    path('castvote', views.castvote, name='castvote'),
    path('vote', views.vote, name='vote'),
]

bulletin/urls.py
from django.urls import path

from . import views

app_name = 'bulletin'
urlpatterns = [
    path('', views.check, name='check'),
]

resist/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('booth/', include('booth.urls')),
    path('bulletin/', include('bulletin.urls')),
    path('register/', include('register.urls')),
    path('supervisor/', include('supervisor.urls')),
    #path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('tabulation/', include('tabulation.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

booth/models.py
from django.db import models

# Create your models here.

booth/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core import serializers
from django.forms.models import model_to_dict
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User


from bulletin.models import Election, Question, Choice, EligibleVoter, AuthenticatedVoter, RegisteredVoter, RegistrationTeller, TabulationTeller, Credential, CredentialShare, CastVote

import requests, json
from Crypto.Random import random
from crypto import ElGamalCrypto as crypto

def is_member(user):
    return user.groups.filter(name='Voter').exists()

def build_question(question):
    choices = list(Choice.objects.filter(question = question).values('id', 'text'))[::-1]
    for choice in range(len(choices)):
        choices[choice]['selection'] = 0
    question_dict = {
        "questionID" : question.id,
        "questionText" : question.text,
        "questionDescription" : question.description,
        "questionMaxChoices" : question.max_choices,
        "numberOfSelectedChoices" : 0,
        "choices" : choices,
    }
    return question_dict

# Create your views here.

def electionactions(request):
    return render(request, 'booth/electionactions.html', {'electionID' : request.POST['electionID']})
    #context_object_name  = ''


def activeelection(request):
    return render(request, 'booth/index.html', {
        'elections' : Election.objects.filter(registration_frozen = True, voting_frozen = False),
   })

@login_required
@user_passes_test(is_member)
def registerindex(request):
    return render(request, 'booth/registerelectionlist.html', {
            'elections' : Election.objects.all()
        })

"""
    The register function helps voters obtain credential shares and build their credential.
    credential = credential_share_value[0] * credential_share_value[1] ...
    The booth initially checks if the voter has already been registered in the past for this election.
    If not, an entry is made in the database.
    A GET request is sent to the register app, where a new credential share is generated and the credential value 
    on the bulletin board gets updated.
    The response from each registration teller is a credential share, which is added to an array and multiplied with the 
    previous value of credential.
"""
@login_required
@user_passes_test(is_member)
def register(request):
    user = request.user
    election = Election.objects.get(election_uuid = request.POST['election_uuid'])
    election_public_key = crypto.PublicKey.from_json(election.public_key)
    eligible_voter = EligibleVoter.objects.get(user = user, election = election)
    authenticated_voter = AuthenticatedVoter.objects.get(eligible_voter = eligible_voter)
    registration_tellers = RegistrationTeller.objects.filter(election = election)
    try:
        registered_voter = RegisteredVoter.objects.get(authenticated_voter = authenticated_voter)
        credential = Credential(registered_voter = registered_voter)
        return render(request, 'booth/error.html', {
            'message' : "Credential Shares already generated for this user."
        })
    except:
        registered_voter = RegisteredVoter(authenticated_voter = authenticated_voter)
        registered_voter.save()
        credential = Credential(registered_voter = registered_voter, encrypted_credential = crypto.ElGamalCrypto.encrypt(message = 1, public_key = election_public_key).to_json())
        credential.save()
    credential_shares = []
    credential = 1
    for registration_teller in registration_tellers:
        try:
            credential_share = CredentialShare.objects.get(registration_teller = registration_teller, credential = credential)
            data = "Credential Share already generated."
        except:
            url = "http://" + request.get_host() + reverse('register:credentialshare', kwargs = {'election_uuid' : election.election_uuid, 'rid' : registration_teller.id, 'public_index' : authenticated_voter.public_index})
            response = requests.get(url)
            data = response.json()
            credential_share_value = data["credential_share"]
            credential = (credential * credential_share_value) % election_public_key.key_parameters.p
            credential_shares.append(credential_share_value)
    encrypted_credential = crypto.ElGamalCrypto.encrypt(message = credential, public_key = election_public_key)
    fake_credential_shares = crypto.generate_fake_credentials(credential_shares = credential_shares)
    fake_credentials = []
    encrypted_fake_credentials = []
    for i in range(0, len(fake_credential_shares)):
        temp = 1
        for j in range(0, len(fake_credential_shares[i])):
            temp = (temp * fake_credential_shares[i][j]) % election_public_key.key_parameters.p
        fake_credentials.append(temp)
        encrypted_fake_credentials.append(crypto.ElGamalCrypto.encrypt(message = fake_credentials[i], public_key = election_public_key))
    print("Encrypted Credential : ")
    print(encrypted_credential)
    public_index = int(authenticated_voter.public_index)
    encrypted_public_index = crypto.ElGamalCrypto.encrypt(message = public_index, public_key = election_public_key)
    downloadable_public_index = {
        "a" : str(encrypted_public_index.a),
        "b" : str(encrypted_public_index.b),
    }
    downloadable_encrypted_credential = {
        "a" : str(encrypted_credential.a),
        "b" : str(encrypted_credential.b),
    }
    downloadable_credential = {
        "credential_shares" : [str(i) for i in credential_shares],
        "credential" : str(credential),
        "encrypted_credential" : downloadable_encrypted_credential,
        "public_index" : downloadable_public_index,
    }
    final_downloadable_fake_credentials = []
    for i in range(0, len(fake_credentials)):
        temp = {
            "credential_shares" : [str(j) for j in fake_credential_shares[i]],
            "credential" : str(fake_credentials[i]),
            "encrypted_credential" : {
                "a" : str(encrypted_fake_credentials[i].a),
                "b" : str(encrypted_fake_credentials[i].b),
            },
            "public_index" : downloadable_public_index,

        }
        final_downloadable_fake_credentials.append(temp)
        
    return render(request, 'booth/credentialdownload.html', {
        'credential' : downloadable_credential,
        'fake_credentials' : final_downloadable_fake_credentials,
    })


def castvote(request):
    vote = json.loads(request.body)
    print(vote)
    election = Election.objects.get(election_uuid = vote['electionUUID'])
    cast_vote = CastVote(election = election, encrypted_credential = vote['encrypted_credential'], encrypted_choices = vote['encrypted_choices'], encrypted_index = vote['public_index'])
    cast_vote.proof_choices = [ {0 : 0} ]
    cast_vote.proof_credential = {0 : 0}
    cast_vote.proof_index = {0 : 0}
    cast_vote.save()
    return HttpResponse(reverse('booth:index'))


def vote(request):
    election = Election.objects.get(election_uuid = request.POST['election_id'])
    downloadable_encrypted_choices = []
    for encrypted_choice in election.encrypted_choices:
        encrypted_choice = json.loads(encrypted_choice)
        temp = {
            "a" : str(encrypted_choice["a"]),
            "b" : str(encrypted_choice["b"]),
        }
        downloadable_encrypted_choices.append(temp)
    public_key = json.loads(election.public_key)
    election_metadata = {
        "electionUUID": str(election.election_uuid),
        "electionName" : election.name,
        "electionOrganization" : election.organization,
        "electionDescription" : election.description,
        "electionPublicKey" : {
            "p" : str(public_key["p"]),
            "q" : str(public_key["q"]),
            "g" : str(public_key["g"]),
            "y" : str(public_key["y"]),
        },
        "electionHelpEmail" : election.help_email,
        "electionCastUrl" : reverse('booth:castvote'),
        "encrypted_choices" : downloadable_encrypted_choices,
    }
    questions_obj = Question.objects.filter(election = election)
    questions_list = [ build_question(question) for question in questions_obj][::-1]
    election_metadata['numberOfQuestions'] = len(questions_list)
    ballot = {
        "electionMetadata" : election_metadata,
        "questions" : questions_list,
    }
    election.save()
    return render(request, 'booth/vote.html', {
        'ballot': ballot,
    })

booth/templates/booth/base.html
{% load static %}

<!DOCTYPE html>
<head>
  <title>{{title}}</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <!--<meta name="viewport" content="min-width=768, max-width:1024, max-height=1000, initial-scale=1, user-scalable=0">-->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width">
  <link rel="apple-touch-icon-precomposed" href="{% static 'booth/style.css' %}" />
  <link rel="stylesheet" href="{% static 'booth/style.css' %}" type="text/css" media="screen" />
  {% block stylesheets %}
  {% endblock %}
  {% block scripts %}
  {% endblock %}
</head>
<body
  {% if request.user_agent.is_mobile %}
    class="mobile"
  {% endif %}
  ontouchstart=""
>
  <section id="header">
  	<header class="container">
  		<input id="button-settings" type="button" class="button icon settings open-settings" value="Settings" style="display: inline-block;"/>
  		<input id="button-help" type="button" class="button icon help open-help" value="Help" style="display: inline-block;" />
  		<input id="button-review" type="button" class="button review" value="Review"/>
      {% block header %}
      {% endblock %}
  	</header>
  </section>

  
  <section id="page">
    <article class="container">
      {% block content %}
      {% endblock %}
    </article>
  </section>


  <section id="footer">
  	<footer class="container">
  		<input id="button-back" type="button" class="button icon back" value="Back"/>
  		<input id="button-cancel" type="button" class="button icon cancel" value="Cancel" />
  		<input id="button-skip" type="button" class="button icon skip" value="Skip" />
      <!--
      <div id="progress">
  			<p><strong><span id="progress-current"><?php echo ballot_current_race(); ?></span></strong> of <strong><span id="progress-total"><?php echo ballot_total_races(); ?></span></strong></p>
  		</div>
      -->
      {% block footer %}
      {% endblock %}
  		<input id="button-next" type="button" class="button icon next" value="Next" />
  		<input id="button-accept" type="button" class="button icon accept green" value="Accept" />
  		<input id="button-cast" type="button" class="button cast green" value="Cast your vote" />
  		<input id="button-return-review" type="button" class="button icon return green" value="Return to review and cast your vote" />
      <input id="button-begin" type="button" class="onscreen double green" value="Start"  />
  	</footer>
  </section>
</body>

booth/templates/booth/credentialdownload.html
{% extends 'booth/base.html' %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'booth/js/createDownload.js' %}"></script>
    <script type="text/javascript">
    window.onload = function() {
        console.log("credential:")
        console.log({{credential | safe}})
        console.log("fake_credential_shares:")
        console.log({{fake_credential_shares | safe}})
        console.log("fake_credentials:")
        console.log({{fake_credentials | safe}})
        console.log("encrypted_fake_credentials:")
        console.log({{encrypted_fake_credentials | safe}})
    }
    </script>
{% endblock %}

{% block header %}

    <a id="button-review" type="button" class="button green review" href = "{% url 'logout' %}" style="display: inline-block;">Logout</a>

{% endblock %}

{% block content %}
    <div id="description" style="height: auto;">
        <h1><strong>Resist</strong></h1>
        <div class = "options">
            <div class = "option">
            <p> Please click below to download your credential:</p>
	        <a id="credentialDownload" type="button" class ="button accept green long"  style="display:inline-block;" download = "credential.json" onclick = "createDownload('credentialDownload', {{credential | safe}});"><p>Download Credential</p></a>
            </div>
            {% for fake_credential in fake_credentials %}
                <div class="option">
                    <p>Please click here to download fake credential:</p>
                    <a id="{{ forloop.counter0 }}" type="button" class ="button accept green long"  style="display:inline-block;" download = "credential.json" onclick = "createDownload('{{forloop.counter0}}', {{fake_credential | safe}});"><p>Download Credential</p></a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

booth/templates/booth/electionactions.html
{% extends 'booth/base.html' %}

{% block content %}
  <form id="my-form" method="post">
    {% csrf_token %}
    <input type="hidden" id="electionID" name="electionID" value={{electionID}} />
  </form>
  <div id="description" style="height: auto;">
      <h1 class="open-primary">
        <strong>Resist</strong>
      </h1>
  </div>
  <div id="content" style="height: auto;">
      <p>What do you want to do?</p>
  </div>
  <div id="options" class="scroll bottom override top" style="height: auto;">
    <div class="option">
      <div id="choice-1" class="choice" onclick="activateChoice('choice-1')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Check Election Bulletin</p>
        </div>
      </div>
    </div>
    <div class="option">
      <div id="choice-2" class="choice" onclick="activateChoice('choice-2')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Register to Vote</p>
        </div>
      </div>
    </div>
    <div class="option">
      <div id="choice-3" class="choice" onclick="activateChoice('choice-3')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Cast a Vote</p>
        </div>
      </div>
    <div>
    <script>
      function activateChoice(choice) {
        if (document.getElementById(choice).classList.contains("active")) {
          document.getElementById(choice).classList.remove("active");
        } else if(document.getElementsByClassName("active")[0]) {
          alert("Uncheck the one you don't want. Then choose the one you want.");
        } else {
          document.getElementById(choice).classList.add("active");
        }
      }
    </script>
  </div>

{% endblock %}

{% block footer %}
  <input id="button-begin" type="button" class="onscreen double green" style = "display: block;" value="Proceed" onclick = "proceed()" />
  <script>
    function proceed(){
      activeChoice = document.getElementsByClassName("active")[0].id;
      console.log(activeChoice);
      if(activeChoice === "choice-1") {
        url = "{% url 'bulletin:check' %}";
      } else if (activeChoice === "choice-2") {
        url = "{% url 'register:start' electionID %}";
      } else if (activeChoice === "choice-3") {
        url = "{% url 'booth:vote' %}";
      }
      document.getElementById("my-form").action = url;
      document.getElementById("my-form").submit();
    }
  </script>
{% endblock %}

booth/templates/booth/error.html
{% extends 'booth/base.html' %}

{% block content %}

    <div id="description" style="height: auto;">
      <h1><strong>Resist</strong></h1>
      <p>{{ message }}</p>
    </div>
{% endblock %}

booth/templates/booth/index.html
{% extends 'booth/base.html' %}

{% block content %}

  <div id="description" style="height: auto;">
      <h1><strong>Resist</strong></h1>
        <form id="go_to_election" method="post" action="{% url 'booth:vote' %}">
            {% csrf_token %}
            <p>List of Active Elections</p>
            <ul>
                {% for election in elections %}
                    <li>
                        <input type="hidden" name="election_id" value={{election.election_uuid}} />
                        <a onclick="document.getElementById('go_to_election').submit(); return false;">{{election.name}}</a>
                    </li>
                {% endfor %}
            </ul>
        </form>
{% endblock %}

booth/templates/booth/registerelectionlist.html
{% extends 'booth/base.html' %}


{% block header %}

    <a id="button-review" type="button" class="button green review" href = "{% url 'logout' %}" style="display: inline-block;">Logout</a>

{% endblock %}


{% block content %}

  <div id="description" style="height: auto;">
      <h1><strong>Resist</strong></h1>
        <form id="go_to_election" method="post" action="{% url 'booth:register' %}">
            {% csrf_token %}
            <p>List of Elections Available for Registration</p>
            <ul>
                {% for election in elections %}
                    {% if election.registration_frozen == False %}
                    <li>
                        <input type="hidden" name="election_uuid" value= {{ election.election_uuid }} />
                        <a onclick="document.getElementById('go_to_election').submit(); return false;">{{election.name}}</a>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </form>
{% endblock %}

booth/templates/booth/vote.html
{% extends 'booth/base.html' %}
{% load static %}
{% block scripts %}
<!-- Crypto JS -->
<script type="text/javascript" src="{% static 'booth/jscrypto/sodium.js' %}"></script>
<script type="text/javascript" src="{% static 'booth/jscrypto/BigInteger.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booth/jscrypto/electionAlgorithms.js' %}"></script>
<script type="text/javascript" src="{% static 'booth/jscrypto/encryptBallot.js' %}"></script>

<!-- Front-end JS -->
<script type="text/javascript" src="{% static 'booth/js/createPlaintextBallot.js' %}"></script>
<script type="text/javascript" src="{% static 'booth/js/displayMetadata.js' %}"></script>
<script type="text/javascript" src="{% static 'booth/js/displayBallot.js' %}"></script>
<script type = "text/javascript">
  window.onload = function() {
    displayMetadata({{ ballot | safe }});
  }
</script>
{% endblock %}

{% block content %}

    <div id="description" style="height: auto;">
    </div>

{% endblock %}