booth/urls.py
from django.urls import path

from . import views

app_name = 'booth'
urlpatterns = [
    path('', views.activeelection, name='index'),
    path('registerindex', views.registerindex, name='registerindex'),
    path('register', views.register, name='register'),
    path('electionactions', views.electionactions, name='electionactions'),
    path('castvote', views.castvote, name='castvote'),
    path('vote', views.vote, name='vote'),
]

bulletin/urls.py
from django.urls import path

from . import views

app_name = 'bulletin'
urlpatterns = [
    path('', views.check, name='check'),
]

resist/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('booth/', include('booth.urls')),
    path('bulletin/', include('bulletin.urls')),
    path('register/', include('register.urls')),
    path('supervisor/', include('supervisor.urls')),
    #path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('tabulation/', include('tabulation.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

supervisor/urls.py
from django.urls import path

from . import views

app_name = 'supervisor'
urlpatterns = [
    #supervisor urls
    path('index/',views.index, name='index'),
    path('createelection/', views.createelection, name='createelection'),
    path('electionlist/', views.electionlist, name='electionlist'),
    path('electionactions/', views.electionactions, name='electionactions'),
    path('generatepublickey', views.generate_public_key, name='generatepublickey'),
    path('registrationkeys', views.registration_keys, name='registrationkeys'),
    path('freezeregistration/', views.freezeregistration, name='freezeregistration'),
    path('freezevoting/', views.freezevoting, name='freezevoting'),
    path('releaseresults/', views.releaseresults, name='releaseresults'),
    path('addelection/', views.addelection, name='addelection'),
    path('createtabulation/', views.createtabulation, name='createtabulation'),
    path('createauth/', views.createvoter, name='createvoter'),
    path('createvoter/', views.createvoter, name='createvoter'),
    path('regvoter/', views.regvoter, name='register'),
]

supervisor/models.py
from django.db import models

# Create your models here.

supervisor/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from bulletin.models import Election, CastVote
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from bulletin.models import Election, TabulationTeller, RegistrationTeller
from tabulation.models import TabulationTellerPrivate
from register.models import RegistrationTellerPrivate
from crypto import ElGamalCrypto as crypto

from threshold_crypto import ThresholdCrypto, ThresholdParameters

def is_member(user):
    return user.groups.filter(name='Supervisor').exists()

# Create your views here.
@login_required
@user_passes_test(is_member)
def index(request):
    return render(request, 'supervisor/index.html')

@login_required
@user_passes_test(is_member)
def createelection(request):
    registration_tellers = User.objects.filter(groups__name='Registration Teller')
    tabulation_tellers = User.objects.filter(groups__name='Tabulation Teller')
    return render(request, 'supervisor/createelection.html', {
        'registrationTellers' : registration_tellers,
        'tabulationTellers' : tabulation_tellers,
    })


@login_required
@user_passes_test(is_member)
def electionlist(request):
    user = request.user
    elections = Election.objects.filter(supervisor=user)
    return render(request, 'supervisor/electionlist.html', {
        'elections' : elections,
    })

@login_required
@user_passes_test(is_member)
def electionactions(request):
    return render(request, 'supervisor/electionactions.html', {
        'electionID' : request.POST['election_id']
    })
    

@login_required
@user_passes_test(is_member)
def generate_public_key(request):
    election = Election.objects.get(election_uuid=request.POST['electionID'])
    if election.public_key:
        return render(request, 'supervisor/electionpublickey.html', {
            'public_key' : election.public_key
        })
    else:
        try:
            tabulation_tellers = TabulationTeller.objects.filter(election=election)
        except:
            raise ValueError("No Tabulation Tellers found for election with id : " + str(request.POST['electionID']))

        (public_key, private_key, key_shares, commitments) = crypto.ElGamalCrypto.generate_dist_key(512, len(tabulation_tellers))
        shared_random_value = crypto.ElGamalCrypto.shared_random_value(public_key.key_parameters)
        for tabulation_teller, key_share in zip(tabulation_tellers, key_shares):
            tabulation_teller_private = TabulationTellerPrivate(user = tabulation_teller.user, election = election, key_share = key_share.to_json(), z = { 'value' : str(shared_random_value) })
            tabulation_teller_private.save()
            tabulation_teller.public_key_share = crypto.PublicKey(key_share.y, key_share.key_parameters).to_json()
            tabulation_teller.save()
        election.public_key = public_key.to_json()
        election.private_key = private_key.to_json()
        commitments_array = [None] * len(commitments)
        for i in range(0, len(commitments)):
            commitments_array[i] = {
                'value' : commitments[i]
            }
        election.key_commitments = commitments_array
        encrypt_one = crypto.ElGamalCrypto.encrypt(message = 1, public_key = public_key, encode = True)        
        encrypt_zero = crypto.ElGamalCrypto.encrypt(message = 0, public_key = public_key, encode = True)        
        election.encrypted_choices = [encrypt_zero.to_json(), encrypt_one.to_json()]
        election.save()
        return render(request, 'supervisor/electionpublickey.html', {
            'public_key' : public_key,
            'key_shares' : key_shares,
        })

@login_required
@user_passes_test(is_member)
def registration_keys(request):
    election = Election.objects.get(election_uuid=request.POST['electionID'])
    registration_tellers = RegistrationTeller.objects.filter(election = election)
    for registration_teller in registration_tellers:
        elgamal_key = crypto.ElGamalCrypto.generate_key(512)
        public_key = crypto.PublicKey(y = elgamal_key.y, key_params = elgamal_key.key_parameters)
        private_key = crypto.PrivateKey(x = elgamal_key.x, key_params = elgamal_key.key_parameters)
        registration_teller_private = RegistrationTellerPrivate(election = election, user = registration_teller.user, private_key = private_key.to_json())
        registration_teller.public_key = public_key.to_json()
        registration_teller_private.save()
        registration_teller.save()
    return render(request, 'supervisor/registrationkeys.html', {
        'keys_generated' : True,
    })

@login_required
@user_passes_test(is_member)
def freezeregistration(request):
    election = Election.objects.get(election_uuid=request.POST['electionID'])
    if (election.registration_frozen == False):
        election.registration_frozen = True
        election.save()
        return render(request, 'supervisor/freezereg.html', {
            'message' : 'Registration for election' + str(election) + 'has been frozen'
        })
    else:
        election.registration_frozen = False
        election.save()
        return render(request, 'supervisor/freezereg.html', {
            'message' : 'Registration for election' + str(election) + 'has been unfrozen'
        })


@login_required
@user_passes_test(is_member)
def freezevoting(request):
    pass


@login_required
@user_passes_test(is_member)
def releaseresults(request):
    pass

def addelection(request):
    election = Election()
    election.name = request.POST['election_name']
    election.organization = request.POST['election_organization']
    election.description = request.POST['election_description']
    election.help_email = request.POST['email']
    #TODO: Change the following to call key generators
    election.public_key = "Filler Public Key"
    election.private_key = "Filler Private Key"
    election.save()
    #TODO: change the redirect URL
    return HttpResponseRedirect(reverse('supervisor:createelection'))

@login_required
@user_passes_test(is_member)
def cheattally(request):
    election = Election.objects.get(supervisor = request.user)
    cast_votes = CastVote.objects.filter(election = election)
    private_key = crypto.PrivateKey.from_json(election.private_key)
    total = []
    
def createvoter(request):
    pass

def createtabulation(request):
    pass

def createauth(request):
    pass

def regvoter(request):
    pass

supervisor/templates/supervisor/base.html
{% load static %}

<!DOCTYPE html>
<head>
  <title>{{title}}</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <!--<meta name="viewport" content="min-width=768, max-width:1024, max-height=1000, initial-scale=1, user-scalable=0">-->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width">
  <link rel="apple-touch-icon-precomposed" href="{% static 'booth/style.css' %}" />
  <link rel="stylesheet" href="{% static 'booth/style.css' %}" type="text/css" media="screen" />
  {% block stylesheets %}
  {% endblock %}
  {% block scripts %}
  {% endblock %}
</head>
<body
  {% if request.user_agent.is_mobile %}
    class="mobile"
  {% endif %}
  ontouchstart=""
>
  <section id="header">
  	<header class="container">
  		<input id="button-settings" type="button" class="button icon settings open-settings" value="Settings" style="display: inline-block;"/>
  		<input id="button-help" type="button" class="button icon help open-help" value="Help" style="display: inline-block;" />
  		<a href="{% url 'logout' %}"><input id="button-review" type="button" class="button review green" value="Logout" style="display: inline-block;"/></a>
  	</header>
  </section>

  
  <section id="page">
    <article class="container">
      {% block content %}
      {% endblock %}
    </article>
  </section>


  <section id="footer">
  	<footer class="container">
  		<input id="button-back" type="button" class="button icon back" value="Back"/>
  		<input id="button-cancel" type="button" class="button icon cancel" value="Cancel" />
  		<input id="button-skip" type="button" class="button icon skip" value="Skip" />
      <!--
      <div id="progress">
  			<p><strong><span id="progress-current"><?php echo ballot_current_race(); ?></span></strong> of <strong><span id="progress-total"><?php echo ballot_total_races(); ?></span></strong></p>
  		</div>
      -->
      {% block footer %}
      {% endblock %}
  		<input id="button-next" type="button" class="button icon next" value="Next" />
  		<input id="button-accept" type="button" class="button icon accept green" value="Accept" />
  		<input id="button-cast" type="button" class="button cast green" value="Cast your vote" />
  		<input id="button-return-review" type="button" class="button icon return green" value="Return to review and cast your vote" />
      <input id="button-begin" type="button" class="onscreen double green" value="Start"  />
  	</footer>
  </section>
</body>

supervisor/templates/supervisor/createelection.html
{% extends 'supervisor/base.html' %}

{% block content %}

    <div id="description">
      <h1><strong>Create Election</strong></h1>
        <aside>
          <form action="{% url 'supervisor:addelection' %}" method="post">
            {% csrf_token %}
            <div class="option">
              <label for="election_name">Election Name: </label>
                <input name="election_name" type="text">
            </div>
            <div class="option">
              <label for="election_organization">Organization: </label>
                <input name="election_organization" type="text">
            </div>
            <div class="option">
              <label for="election_description">Description: </label>
                <input name="election_description" type="text">
            </div>
            <div class="option">
              <label for="email">Enter email for election support:</label>
                <input type="email" name="email" id="email" required>
            </div>
        </aside>
    </div>
{% endblock %}

{% block footer %}
    <button id="button-cast" type="sumbit" class="onscreen button cast green" value="Create Election">Create Election</button>
{% endblock %}

supervisor/templates/supervisor/electionactions.html
{% extends 'supervisor/base.html' %}

{% block content %}
  <form id="my-form" method="post">
    {% csrf_token %}
    <input type="hidden" id="electionID" name="electionID" value={{electionID}} />
  </form>
  <div id="description" style="height: auto;">
      <h1 class="open-primary">
        <strong>Resist</strong>
      </h1>
  </div>
  <div id="content" style="height: auto;">
      <p>What do you want to do?</p>
  </div>
  <div id="options" class="scroll bottom override top" style="height: auto;">
    <div class="option">
      <div id="choice-1" class="choice" onclick="activateChoice('choice-1')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Generate Election Public Key</p>
        </div>
      </div>
    </div>
    <div class="option">
      <div id="choice-2" class="choice" onclick="activateChoice('choice-2')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Generate Keys for Registration Tellers</p>
        </div>
      </div>
    </div>
    <div class="option">
      <div id="choice-3" class="choice" onclick="activateChoice('choice-3')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Freeze Registration</p>
        </div>
      </div>
    </div>
    <div class="option">
      <div id="choice-4" class="choice" onclick="activateChoice('choice-4')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Freeze Voting</p>
        </div>
      </div>
    </div>
    <div class="option">
      <div id="choice-5" class="choice" onclick="activateChoice('choice-5')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Release Results</p>
        </div>
      </div>
    <div>
  </div>
    <script>
      function activateChoice(choice) {
        if (document.getElementById(choice).classList.contains("active")) {
          document.getElementById(choice).classList.remove("active");
        } else if(document.getElementsByClassName("active")[0]) {
          alert("Uncheck the one you don't want. Then choose the one you want.");
        } else {
          document.getElementById(choice).classList.add("active");
        }
      }
    </script>

{% endblock %}

{% block footer %}
  <input id="button-begin" type="button" class="onscreen double green" style = "display: block;" value="Proceed" onclick = "proceed()" />
  <script>
    function proceed(){
      activeChoice = document.getElementsByClassName("active")[0].id;
      console.log(activeChoice);
      if(activeChoice === "choice-1") {
        url = "{% url 'supervisor:generatepublickey' %}";
      } else if (activeChoice === "choice-2") {
        url = "{% url 'supervisor:registrationkeys' %}";
      } else if (activeChoice === "choice-3") {
        url = "{% url 'supervisor:freezeregistration' %}";
      } else if (activeChoice === "choice-4") {
        url = "{% url 'supervisor:releaseresults' %}";
      }
      document.getElementById("my-form").action = url;
      document.getElementById("my-form").submit();
    }
  </script>
{% endblock %}

supervisor/templates/supervisor/electionlist.html
{% extends 'supervisor/base.html' %}

{% block content %}

  <div id="description" style="height: auto;">
      <h1><strong>Resist</strong></h1>
        <form id="go_to_election" method="post" action="{% url 'supervisor:electionactions' %}">
            {% csrf_token %}
            <p>List of Active Elections</p>
            <ul>
                {% for election in elections %}
                    {% if election.results_released == False %}
                    <li>
                        <input type="hidden" name="election_id" value={{election.election_uuid}} />
                        <a onclick="document.getElementById('go_to_election').submit(); return false;">{{election.name}}</a>
                    </li>
                    {% else %}
                    <p>No active elections</p>
                    {% endif %}
                {% endfor %}
            </ul>
            <p>List of Frozen Elections</p>
            <ul>
                {% for election in elections %}
                    {% if election.results_released == True %}
                    <li>
                        <input type="hidden" name="election_id" value={{election.election_uuid}} />
                        <a onclick="document.getElementById('go_to_election').submit(); return false;">{{election.name}}</a>
                    </li>
                    {% else %}
                    <p>No inactive elections</p>
                    {% endif %}
                {% endfor %}
            </ul>
        </form>
{% endblock %}

supervisor/templates/supervisor/electionpublickey.html
{% extends 'supervisor/base.html' %}
{% load static%}
{% block scripts %}

    <script type="text/javascript" src="{% static 'supervisor/js/createDownload.js' %}"></script>
    <script type = "text/javascript">
        window.onload = function() {
            createDownload({{ public_key | safe }});
        }
    </script>

{% endblock %}

{% block content %}

    <h1><strong>Resist</strong></h1>
    {% if public_key %}
        <p>The election public key has been generated. Click the button below to download the public key.</p>
    {% else %}
        <p>Click the button below to generate a public key for this election.</p>
    {% endif %}

{% endblock %}

{% block footer %}

    <a id="publicKeyDownload" type="button" class="button accept green long" value="Download Public Key" style="display:block;"></a>

{% endblock %}

supervisor/templates/supervisor/freezereg.html
{% extends 'supervisor/base.html' %}

{% block content %}

    <div id="description" style="height: auto;">
      <h1><strong>Resist</strong></h1>
      <p>{{ message }}</p>
    </div>
{% endblock %}

supervisor/templates/supervisor/index.html
{% extends 'supervisor/base.html' %}

{% block content %}
  <form id="my-form" method="post">
    {% csrf_token %}
  </form>
  <div id="content" style="height: auto;">
      <p>What do you want to do?</p>
  </div>
  <div id="options" class="scroll bottom override top" style="height: auto;">
    <div class="option">
      <div id="choice-1" class="choice" onclick="activateChoice('choice-1')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Create a new election</p>
        </div>
      </div>
    </div>
    <div class="option">
      <div id="choice-2" class="choice" onclick="activateChoice('choice-2')">
        <div class="vote"></div>
        <div class="desc">
          <p class="candidate">Manage an Existing Election</p>
        </div>
      </div>
    </div>
    <script>
      function activateChoice(choice) {
        if (document.getElementById(choice).classList.contains("active")) {
          document.getElementById(choice).classList.remove("active");
        } else if(document.getElementsByClassName("active")[0]) {
          alert("Uncheck the one you don't want. Then choose the one you want.");
        } else {
          document.getElementById(choice).classList.add("active");
        }
      }
    </script>
  </div>

{% endblock %}

{% block footer %}
  <input id="button-begin" type="button" class="onscreen double green" style = "display: block;" value="Proceed" onclick = "proceed()" />
  <script>
    function proceed(){
      activeChoice = document.getElementsByClassName("active")[0].id;
      console.log(activeChoice);
      if(activeChoice === "choice-1") {
        url = "{% url 'admin:index' %}";
      } else if (activeChoice === "choice-2") {
        url = "{% url 'supervisor:electionlist' %}";
      } else if (activeChoice === "choice-3") {
        url = "{% url 'bulletin:check' %}";
      } else {
        url = "{% url 'booth:index'%}";
      }
      document.getElementById("my-form").action = url;
      document.getElementById("my-form").submit();
    }
  </script>
{% endblock %}

supervisor/templates/supervisor/registrationkeys.html
{% extends 'supervisor/base.html' %}
{% load static%}

{% block content %}

    <h1><strong>Resist</strong></h1>
    {% if keys_generated == True %}
        <p>Keys for registration tellers have been generated.</p>
    {% else %}
        <p>Generating registration keys</p>
    {% endif %}

{% endblock %}